version: "3.9"
services:
  backend:
    build: ./backend
    container_name: transcriber-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - faster-whisper
    restart: always

  faster-whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: faster-whisper
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=faster_whisper
    ports:
      - 9000:9000
    restart: unless-stopped
 

  frontend:
    image: nginx:alpine
    container_name: transcriber-frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
